version: '3'

volumes:
  postgres-data:
    driver: local

  cache:
    driver: local

networks:
  my-network:
    external: true

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - my-network